name: Daily Letterboxd Scraper

on:
  schedule:
    - cron: "0 14 * * *"  # Run at 03:15 UTC daily
  workflow_dispatch:      # Allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python pop_film_scraper.py

      - name: Commit and push data
        run: |
          export TZ=America/Los_Angeles
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add letterboxd_popular_history.csv
          git commit -m "Daily update: $(date '+%Y-%m-%d %H:%M %Z')"
          git push

