name: Daily Letterboxd Scraper

on:
  schedule:
    - cron: "15 3 * * *"  # Run at 03:15 UTC daily
  workflow_dispatch:      # Allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python scrape_letterboxd.py

      - name: Commit and push new snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add letterboxd_popular_history.csv
          git commit -m "Add snapshot for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
